# Generated by Django 3.1.3 on 2021-01-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201219_0921'),
        ('core', '0005_auto_20201219_1947'),
    ]

    operations = [
    ]
