# Generated by Django 3.1.3 on 2020-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='http://', max_length=200),
            preserve_default=False,
        ),
    ]
