# Generated by Django 3.1.3 on 2020-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201127_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_number',
            field=models.IntegerField(default=1),
        ),
    ]
