# Generated by Django 3.1.3 on 2020-12-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_number',
        ),
    ]
