# Generated by Django 3.1.3 on 2020-11-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_form", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={"verbose_name_plural": "Contact Forms"},
        ),
    ]
