# Generated by Django 3.1.3 on 2020-12-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='s', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='testt', max_length=20),
            preserve_default=False,
        ),
    ]
