# Generated by Django 3.1.3 on 2021-01-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210114_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='order',
        ),
    ]
