# Generated by Django 3.1.3 on 2021-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_productlist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
